"""Reviewed static Chinese content for every bundled Reading item."""

from __future__ import annotations


READING_REVIEW_SEEDS: dict[str, tuple[str, str]] = {
    "AR-V1-001-Q01": ("因此，种植屋顶的价值不在于造一个迷你花园，而在于改变建筑物及周边空间的热量和水分表现。", "A 段强调的是环境功能，不是把屋顶当作普通公共花园。"),
    "AR-V1-001-Q02": ("收益大小会变化；气候也会影响结果；研究者因此越来越报告性能范围。", "固定数值忽略了植物状态、湿度和地区气候带来的差异。"),
    "AR-V1-001-Q03": ("隔热很好的新办公楼可能节能变化很小，而较旧的单层建筑反应可能更明显。", "原文直接比较两类建筑，较旧单层建筑的收益更大。"),
    "AR-V1-001-Q04": ("这并不表示绿化屋顶吸收每一场暴雨；储水层饱和后，多余雨水仍会流走。", "题干的 all 与原文的饱和后仍径流相矛盾，因此为 False。"),
    "AR-V1-001-Q05": ("景天属植物之所以常用，是因为它们能适应这些条件且重量较轻。", "耐受屋顶环境和较轻重量正是题干 widely used 的原因。"),
    "AR-V1-001-Q06": ("汉堡曾提供补贴，既可用于新建，也可用于合适的改造。", "原文只提补贴，没有说所有新商业建筑都被强制安装。"),
    "AR-V1-001-Q07": ("收益大小会变化，气候也会影响冷却效果。", "B 段核心是为什么不同条件下的降温结果不完全相同。"),
    "AR-V1-001-Q08": ("生态学家建议把屋顶视为连接更大栖息地的跳板。", "D 段既讲耐受植物，也讲其在生态连接中的辅助作用。"),
    "AR-V1-001-Q09": ("一些政府绘制高热暴露、树冠少或易内涝地区，并对这些地区的屋顶给予更多支持。", "F 段讲的是按公共收益和需求把支持投向优先社区。"),
    "AR-V1-002-Q01": ("博物馆会挑选耐用物件、制作复制品、培训员工并制定接触方式。", "受控触摸是经过设计的流程，不是允许观众随意触碰全部展品。"),
    "AR-V1-002-Q02": ("参与者必须在特定时间加入特定团体，主展厅本身并未改变。", "早期触摸活动的限制来自预约群体和固定时段。"),
    "AR-V1-002-Q03": ("把很小的硬币放大，可以让已经磨损的符号更容易被触摸辨认。", "放大复制品的目的在于让细小或磨损细节可感知。"),
    "AR-V1-002-Q04": ("整合式触觉资源也有益于通过比较实物和视觉信息学习的儿童与成人。", "原文明说受益者不限于视障者，因此判断为 True。"),
    "AR-V1-002-Q05": ("是否可触摸要逐件决定；仅凭年代不能判断物品是否过于脆弱。", "题干把唯一依据说成 age alone，与原文相反。"),
    "AR-V1-002-Q06": ("原文没有提供大多数复制品在哪里制造的信息。", "提到扫描和打印不等于说明制造地点或多数博物馆的做法。"),
    "AR-V1-002-Q07": ("这种区分让参观者分别思考：这件原物经历了什么，以及它的形状能说明什么。", "C 段对比原件的历史身份与复制品提供的形态信息。"),
    "AR-V1-002-Q08": ("口头描述最有用的方式是引导注意，但不替参观者规定解释。", "E 段主旨是有结构地探索，同时避免强加判断。"),
    "AR-V1-002-Q09": ("无障碍不是放进展厅就结束，而是设计、维护和访客反馈之间持续的关系。", "F 段讨论学习评估与长期维护，而非一次性安装。"),
    "AR-V1-003-Q01": ("车辆装载物更少，司机还要找地址，而合法装卸位可能已被占用。", "最后一公里成本高来自小批量、寻找地址和重复停靠等时间损耗。"),
    "AR-V1-003-Q02": ("多家承运商可能在数分钟内到同一条街，每辆车都没有装满。", "旧项目改善单车油耗，却没有解决同街重复进车的问题。"),
    "AR-V1-003-Q03": ("如果货量太低或时间安排不当，额外搬运会抵消运输节省。", "微型枢纽并非任何条件下都节省，关键在足够且合时的货流。"),
    "AR-V1-003-Q04": ("最高速度更低并不一定意味着配送更慢。", "货运自行车可更靠近目的地停车并走受限路线，能抵消速度劣势。"),
    "AR-V1-003-Q05": ("货运自行车适合小而可预测的包裹，但不适合所有配送。", "题干把适用范围扩大为 every type，与原文的分工方案冲突。"),
    "AR-V1-003-Q06": ("原文没有提供储物柜用户的配送收费信息。", "便利性和交通影响不能推出收费更低。"),
    "AR-V1-003-Q07": ("研究者认为稀缺资源应是街道空间，而不只是车辆本身。", "B 段承认单车效率有用，但指出它不足以解决重复占用街道。"),
    "AR-V1-003-Q08": ("环境收益来自按任务匹配车辆，而不是给每次运输套上流行技术。", "D 段按大小、紧急程度和处理要求选择配送方式。"),
    "AR-V1-003-Q09": ("多个项目把标准化汇总指标发送到中立平台。", "F 段在衡量协同系统时兼顾信息共享与商业隐私。"),
    "AR-V2-001-Q01": ("每种数据来源都有局限，因此研究者把预测的阴影与街道层面的重复观察进行比较。", "比较的目的就是校正模型或遥感资料的不完整和过时。"),
    "AR-V2-001-Q02": ("设计者不再给出唯一完美路线，而是提供最快、最凉爽和均衡等选择。", "不同用户重视距离、安全和降温不同，所以需要多种优先级路线。"),
    "AR-V2-001-Q03": ("它最强的作用可能是诊断：显示保护在哪里消失，并让规划者在建设前测试方案。", "shade mapping 的核心价值是发现缺口并评估未来干预。"),
    "AR-V2-001-Q04": ("考虑阴影的路线长四分钟，却把直射日光暴露减少了一半以上。", "题干的 slightly longer 与原文 four minutes longer 一致，因此为 True。"),
    "AR-V2-001-Q05": ("单纯统计树木可能掩盖问题；围栏后的大树冠不能帮助在公交站等候的人。", "树总数不等于公众可获得的阴影，题干的 always 因此错误。"),
    "AR-V2-001-Q06": ("早期实验说明时间为何重要。", "文中没有给出首个应用的大学或洲别，不能补充推断。"),
    "AR-V2-001-Q07": ("城市研究者开始像对待排水设施或公交站一样严肃地绘制这一不断变化的资源。", "A 段把随时间移动的阴影提升为规划基础设施议题。"),
    "AR-V2-001-Q08": ("最终地图不是单张图，而是一系列变化图，类似天气预报。", "B 段的重点是整合不完美资料，形成按时间变化的地图。"),
    "AR-V2-001-Q09": ("研究者考察阴影路段与学校、诊所和市场等日常目的地之间的连接。", "D 段衡量的是连通的可达性，而不是树木总数。"),
    "AR-V2-001-Q10": ("这一理念扩展到热应急之外，但研究者反对把阴影变成看似过于精确的数值。", "G 段既谈更广应用，也强调诚实呈现不确定性。"),
    "AR-V2-002-Q01": ("环境结果取决于模块供应多久、人们是否真正更换，以及模块结构增加多少材料。", "可拆部件本身不保证可持续性，还受支持、行为和材料成本影响。"),
    "AR-V2-002-Q02": ("替换的相机或显示屏可能物理上兼容，却因系统期待原部件序列号而被拒绝。", "阻碍维修的是软件对新部件身份的拒绝，而不是零件无法安装。"),
    "AR-V2-002-Q03": ("效率降低消费成本或努力，因此反而可能增加消费。", "rebound 指更容易升级诱发更多购买，而非单次产品更省。"),
    "AR-V2-002-Q04": ("螺丝、卡扣和标准插座可以拆卸，但会占用空间。", "题干的占用更多内部空间与原文直接一致。"),
    "AR-V2-002-Q05": ("大多数客户可能需要电池，而六年后要求更换扬声器的人很少。", "题干把 very few 说成 most，形成明确矛盾。"),
    "AR-V2-002-Q06": ("社区维修工作坊展示了易维修产品的另一种价值。", "没有出现它们最早出现的年代，故为 Not Given。"),
    "AR-V2-002-Q07": ("这是关于体积、耐用性、制造时间和维修者技能预期的权衡系统。", "B 段讲可接近性带来的工程取舍。"),
    "AR-V2-002-Q08": ("商业模式决定这种设计能否在发布后继续存在。", "D 段聚焦长期零件供应如何获得可行的资金支持。"),
    "AR-V2-002-Q09": ("参与者学习故障诊断、安全处理以及自己能维修到什么程度。", "F 段既讲社区维修的学习价值，也讲其边界。"),
    "AR-V2-002-Q10": ("维护、专业维修、再利用和负责任回收应在第一台产品出厂前就被规划。", "G 段总结可信维修生态系统必须具备全生命周期条件。"),
    "AR-V2-003-Q01": ("学习者有足够背景形成看法，但会遇到一个重要的知识缺口。", "有意义且可探究的缺口，才是 productive uncertainty。"),
    "AR-V2-003-Q02": ("有些教师收集匿名数字回答，既保留思考投入，又不把错误贴到某个学生身上。", "匿名回答的价值在于降低尴尬，同时保留对预测的投入。"),
    "AR-V2-003-Q03": ("评分量表关注证据质量、修订的逻辑，以及界定未知内容的能力。", "应奖励基于证据的调整，而不是单纯犹豫。"),
    "AR-V2-003-Q04": ("如果教师立刻解释答案，学生可能永远不会检查自己的假设。", "即时讲解会截断检验假设的过程，所以题干为 True。"),
    "AR-V2-003-Q05": ("实验室中的安全关键程序不应通过试错来发现。", "题干的 recommends 与原文 should not 相反。"),
    "AR-V2-003-Q06": ("教师还必须注意参与机会不平等。", "文章没有按班级规模比较受益程度，不能推断。"),
    "AR-V2-003-Q07": ("教育研究者研究另一种可能：经过精心设计时，不确定性可以支持学习。", "A 段把不确定性介绍为被设计的学习机会。"),
    "AR-V2-003-Q08": ("学习者先承诺一个预测，再与另一个案例比较、讨论差异，之后才得到正式术语。", "C 段按预测、比较、解释的顺序组织活动。"),
    "AR-V2-003-Q09": ("这些惯例帮助学生把不确定性看作观点的特征，而不是提出观点者的缺陷。", "D 段讨论让修订在心理上安全的语言与讨论方式。"),
    "AR-V2-003-Q10": ("最终目标不是永久怀疑，而是经过校准的自信。", "G 段把课堂中的疑问导向负责且可调整的判断。"),
    "AR-V2-004-Q01": ("它把切碎的秸秆、种壳或锯末等农业残余物结合成轻质复合材料。", "菌丝在材料中充当把植物颗粒粘结起来的生物黏合剂。"),
    "AR-V2-004-Q02": ("在面板后留下空气层，可以改善吸声而不显著增加材料。", "改善来自 air gap 改变声学行为，而不是加厚面板。"),
    "AR-V2-004-Q03": ("更换两次的面板，可能比使用数十年的传统面板留下更大的足迹。", "制造影响较低也可能被频繁更换抵消。"),
    "AR-V2-004-Q04": ("数日内，白色菌丝会在颗粒间扩散并把它们连接起来。", "题干描述与原文的生长过程一致，因此为 True。"),
    "AR-V2-004-Q05": ("菌丝复合材料通常在中频和高频表现最好。", "题干若把性能归到其他频段，就与原文不符。"),
    "AR-V2-004-Q06": ("生产从选择干净的原料开始。", "没有说明生产从何时或何种额外步骤开始，题干之外的信息不可补充。"),
    "AR-V2-004-Q07": ("面板逐渐发展，因此制造计划必须计入生物生长所需时间。", "该段核心是受生物生长控制的制造过程。"),
    "AR-V2-004-Q08": ("认证评估最终产品，而不是其吸引人的生物故事。", "H 段由自然差异转向可验证、可认证的性能。"),
    "AR-V2-004-Q09": ("最佳策略取决于当地系统。", "I 段指出报废后的选择取决于产品类型和所在地条件。"),
    "AR-V2-004-Q10": ("它不是由废物长成的神奇物体，而是安静且循环空间中经过谨慎工程化的一层。", "结论认可其应用潜力，同时拒绝夸大为万能方案。"),
    "AR-V2-005-Q01": ("明亮环境能支持警觉表现，但临近下班的同样光照可能延迟睡眠。", "关键是光照时机：可支持工作，也可能妨碍之后入睡。"),
    "AR-V2-005-Q02": ("一位员工偏好的亮度可能干扰旁边休息的同事，因此分区和遮挡通常优于全屋单一控制。", "不同需求应通过局部分区解决，而不是改变所有人的光线。"),
    "AR-V2-005-Q03": ("强有力的评估会记录原始条件、分阶段引入变化，并比较多个结果。", "可靠评估不是只看一个结果，而是有基线、分阶段和多指标。"),
    "AR-V2-005-Q04": ("由于老化的眼睛透光更少，年长员工完成同样视觉任务通常需要更多光。", "题干与原文的因果关系一致，因此为 True。"),
    "AR-V2-005-Q05": ("过渡应逐渐进行；突然变暗可能让人以为设备故障。", "题干若说 sudden dimming 合适，就与原文冲突。"),
    "AR-V2-005-Q06": ("动态时间表不是普遍处方。", "原文没有为所有人给出统一排程，不能延伸成绝对说法。"),
    "AR-V2-005-Q07": ("设计者以群体证据为起点，再提供安全范围，而不是声称每个人都有精确生物设定。", "该段强调随时间调整，但不宣称存在唯一完美时间表。"),
    "AR-V2-005-Q08": ("信息可以帮助员工选择，而监控或施压可能把责任转移出去。", "该段讨论支持夜班外生活时必须清楚保护隐私边界。"),
    "AR-V2-005-Q09": ("调试时表现良好的时间表，日常使用中可能逐渐变得不准确。", "该段核心是持续校准复杂系统。"),
    "AR-V2-005-Q10": ("良好的夜班照明因此是一项服务，而不是一次性安装。", "结论把照明看作可调、需维护且主张有限的服务。"),
}


READING_VOCABULARY_SEEDS: dict[str, tuple[tuple[str, str, str, str, str, str, str], ...]] = {
    "AR-V1-001": (("living roofs", "/ˈlɪvɪŋ ruːfs/", "noun phrase", "绿化屋顶", "roofs covered with vegetation", "green roofs", "阅读中常用来讨论城市环境措施"), ("humidity", "/hjuːˈmɪdəti/", "noun", "湿度", "amount of water vapour in air", "moisture level", "注意它会影响性能范围"), ("saturated", "/ˈsætʃəreɪtɪd/", "adjective", "饱和的", "filled so no more can be absorbed", "fully soaked", "判断题常用作否定绝对化说法的证据"), ("sedums", "/ˈsiːdəmz/", "noun", "景天属植物", "hardy low-growing plants", "drought-tolerant plants", "专有植物名可作为填空拼写词"), ("structural weight", "/ˈstrʌktʃərəl weɪt/", "noun phrase", "结构承重负荷", "weight a structure must support", "load requirement", "常与轻重比较搭配"), ("stepping stones", "/ˈstepɪŋ stəʊnz/", "noun phrase", "生态跳板", "small links between habitats", "ecological links", "注意比喻义而非字面石头"), ("retrofits", "/ˈretrəʊfɪts/", "noun", "改造项目", "upgrades added to existing buildings", "modernisation", "区分新建与既有建筑改造"), ("heat exposure", "/hiːt ɪkˈspəʊʒə/", "noun phrase", "热暴露", "amount of exposure to heat", "thermal risk", "城市环境题常考风险指标")),
    "AR-V1-002": (("controlled touch", "/kənˈtrəʊld tʌtʃ/", "noun phrase", "受控触摸", "planned handling under rules", "supervised handling", "注意 controlled 表示有规则而非自由接触"), ("robust", "/rəʊˈbʌst/", "adjective", "坚固耐用的", "strong enough for use", "durable", "可用于物品是否适合触摸"), ("replicas", "/ˈreplɪkəz/", "noun", "复制品", "accurate copies of originals", "reproductions", "区分原件与复制品的信息价值"), ("tactile", "/ˈtæktaɪl/", "adjective", "触觉的", "related to touch", "touch-based", "常与 resources 或 map 搭配"), ("vulnerable", "/ˈvʌlnərəbəl/", "adjective", "脆弱易损的", "easily damaged", "fragile", "判断时不能仅以年代推断脆弱性"), ("orientation", "/ˌɔːriənˈteɪʃən/", "noun", "导向说明", "guidance for finding one’s way", "wayfinding", "段落标题题的中心词"), ("interpretation", "/ɪnˌtɜːprəˈteɪʃən/", "noun", "解读", "an explanation of meaning", "reading", "注意 guide attention 不等于 dictate interpretation"), ("maintenance", "/ˈmeɪntənəns/", "noun", "维护", "work to keep something working", "upkeep", "长期无障碍服务的核心条件")),
    "AR-V1-003": (("parcel", "/ˈpɑːsəl/", "noun", "包裹", "a package sent to someone", "package", "城市配送话题高频词"), ("loading spaces", "/ˈləʊdɪŋ speɪsɪz/", "noun phrase", "装卸车位", "places reserved for loading", "delivery bays", "定位成本原因时注意复数"), ("microhub", "/ˈmaɪkrəʊhʌb/", "noun", "微型配送枢纽", "small local distribution centre", "urban hub", "不要默认它一定更节能"), ("cargo cycles", "/ˈkɑːɡəʊ ˈsaɪkəlz/", "noun phrase", "货运自行车", "bicycles designed to carry goods", "freight bikes", "常与最后一公里配送比较"), ("segmentation", "/ˌseɡmenˈteɪʃən/", "noun", "分类分工", "division into suitable groups", "task matching", "用于说明按需求匹配方案"), ("aggregated", "/ˈæɡrɪɡeɪtɪd/", "adjective", "汇总的", "combined into a total", "summarised", "常用于隐私保护的数据表达"), ("parcel locker", "/ˈpɑːsəl ˈlɒkə/", "noun phrase", "包裹自提柜", "secure box for collecting parcels", "collection locker", "不能从便利性推断收费"), ("scarce resource", "/skeəs rɪˈzɔːs/", "noun phrase", "稀缺资源", "something limited in supply", "limited asset", "概括段落主旨时关注作者重新定义的资源")),
    "AR-V2-001": (("shade-aware", "/ʃeɪd əˈweə/", "adjective", "考虑阴影条件的", "designed using shade information", "cooling-focused", "复合形容词常用于路线题"), ("street level", "/striːt ˈlevəl/", "noun phrase", "街道层面", "at ground level in streets", "on-the-ground", "与遥感模型形成证据互补"), ("diagnostic", "/ˌdaɪəɡˈnɒstɪk/", "adjective", "诊断性的", "used to identify a problem", "analytical", "不是医疗语境时也表示发现缺口"), ("canopy", "/ˈkænəpi/", "noun", "树冠层", "upper layer of tree branches", "tree cover", "树冠总量不等于公共可达阴影"), ("infrastructure", "/ˈɪnfrəstrʌktʃə/", "noun", "基础设施", "basic systems serving a place", "public system", "标题题常考抽象功能定位"), ("confidence levels", "/ˈkɒnfɪdəns ˈlevəlz/", "noun phrase", "置信程度", "stated certainty of information", "uncertainty range", "学术写作中避免过度确定"), ("crowdsourced", "/ˈkraʊdsɔːst/", "adjective", "众包的", "collected from many users", "user-reported", "需注意资料仍要核查"), ("direct-sun exposure", "/dəˈrekt sʌn ɪkˈspəʊʒə/", "noun phrase", "直射日光暴露", "time spent in direct sunlight", "sun exposure", "数字比较题要同时核对时间和比例")),
    "AR-V2-002": (("modular", "/ˈmɒdjələ/", "adjective", "模块化的", "made of separable parts", "component-based", "不要把模块化直接等同于可持续"), ("serial number", "/ˈsɪəriəl ˈnʌmbə/", "noun phrase", "序列号", "unique identifying number", "device identity", "软件配对题的关键名词"), ("rebound", "/rɪˈbaʊnd/", "noun", "反弹效应", "increased use after efficiency gains", "backfire effect", "注意效率提高可能反而增加总消费"), ("disassembly", "/ˌdɪsəˈsembli/", "noun", "拆解", "taking something apart", "dismantling", "常与 screws、clips、sockets 搭配"), ("inventory", "/ˈɪnvəntri/", "noun", "库存", "stored goods available for use", "stock", "长期零件供应的商业难题"), ("professional repair", "/prəˈfeʃənəl rɪˈpeə/", "noun phrase", "专业维修", "repair by trained workers", "specialist repair", "社区维修并不替代所有专业路径"), ("reuse", "/ˌriːˈjuːs/", "noun", "再利用", "use again for another purpose", "repurposing", "循环经济链条中的一环"), ("recycling", "/ˌriːˈsaɪklɪŋ/", "noun", "回收再生", "processing material for new use", "material recovery", "结论题关注生命周期规划")),
    "AR-V2-003": (("productive uncertainty", "/prəˈdʌktɪv ʌnˈsɜːtnti/", "noun phrase", "富有成效的不确定性", "useful unresolved gap for learning", "designed doubt", "核心概念需结合可探究性理解"), ("anonymous", "/əˈnɒnɪməs/", "adjective", "匿名的", "without a named identity", "unidentified", "用于降低公开犯错压力"), ("rubrics", "/ˈruːbrɪks/", "noun", "评分量表", "criteria for assessment", "marking criteria", "注意量表评价的是证据和修订逻辑"), ("assumptions", "/əˈsʌmpʃənz/", "noun", "假设", "beliefs accepted without proof", "prior beliefs", "即时讲解会阻断检验假设"), ("safety-critical", "/ˈseɪfti ˈkrɪtɪkəl/", "adjective", "安全关键的", "where mistakes risk safety", "high-risk", "不能套用试错学习模式"), ("trial and error", "/ˌtraɪəl ən ˈerə/", "noun phrase", "试错法", "learning by repeated attempts", "experimentation", "注意在实验室安全程序中被明确排除"), ("calibrated confidence", "/ˈkælɪbreɪtɪd ˈkɒnfɪdəns/", "noun phrase", "校准后的自信", "confidence matched to evidence", "measured confidence", "结论常考不是绝对自信或永久怀疑"), ("participation", "/pɑːˌtɪsɪˈpeɪʃən/", "noun", "参与", "taking part in an activity", "engagement", "文中提醒关注参与机会不均")),
    "AR-V2-004": (("mycelium", "/maɪˈsiːliəm/", "noun", "菌丝体", "network of fungal threads", "fungal network", "材料构成题的核心术语"), ("agricultural residues", "/ˌæɡrɪˈkʌltʃərəl rɪˈzɪdjuːz/", "noun phrase", "农业残余物", "leftover plant materials", "farm by-products", "注意 residue 常用复数"), ("composite", "/ˈkɒmpəzɪt/", "noun", "复合材料", "material made from combined parts", "combined material", "与 binder 的功能关系常考"), ("absorption", "/əbˈzɔːpʃən/", "noun", "吸声", "taking in sound energy", "sound uptake", "区别于隔音 sound insulation"), ("air gap", "/eə ɡæp/", "noun phrase", "空气层", "empty space behind a surface", "air space", "用机制解释性能而非材料增重"), ("footprint", "/ˈfʊtprɪnt/", "noun", "环境足迹", "total environmental impact", "impact", "寿命和更换频率会改变足迹"), ("certification", "/ˌsɜːtɪfɪˈkeɪʃən/", "noun", "认证", "official proof of standards", "approval", "考查最终性能而非宣传故事"), ("circular", "/ˈsɜːkjələ/", "adjective", "循环型的", "designed for reuse and recovery", "resource-cycling", "常与循环经济及生命周期搭配")),
    "AR-V2-005": (("night shift", "/naɪt ʃɪft/", "noun phrase", "夜班", "work done at night", "overnight work", "全文主题词"), ("alert performance", "/əˈlɜːt pəˈfɔːməns/", "noun phrase", "警觉表现", "ability to perform while alert", "vigilance", "注意支持工作不等于支持睡眠"), ("zoning", "/ˈzəʊnɪŋ/", "noun", "分区", "dividing a space into areas", "area control", "用于回应不同员工的光照需求"), ("shielding", "/ˈʃiːldɪŋ/", "noun", "遮挡", "blocking unwanted light", "screening", "常与 zoning 并列"), ("baseline", "/ˈbeɪslaɪn/", "noun", "基线", "original condition for comparison", "starting point", "评估设计需先记录基线"), ("ageing eye", "/ˈeɪdʒɪŋ aɪ/", "noun phrase", "老化的眼睛", "eye that transmits less light with age", "older vision", "因果关系题注意 because"), ("dimming", "/ˈdɪmɪŋ/", "noun", "调暗", "making light less bright", "reducing brightness", "sudden 与 gradual 是判断证据"), ("commissioning", "/kəˈmɪʃənɪŋ/", "noun", "调试投用", "testing a system before use", "initial setup", "系统初期表现好仍需日常校准")),
}
